### ISSUE TITLE
Is it possible to extract the output geometries as an sf object?

### ISSUE THREAD

**Issue by arthurwelle** [stla/sphereTessellation#2]
Hi, 
I was trying to do a sphere voronoi tessellation in R with no luck. Yesterday I started a bounty on SO (https://stackoverflow.com/questions/68324079/how-to-truly-calculate-a-spherical-voronoi-diagram-using-sf). Browsing github I found Michal Summer attempt (https://mdsumner.github.io/vorsph/index.html) and now yours! 
I´m wondering if the resulted tessallation can be converted to a sf object (one that I could manipulate further)?
In any case nice job!
Best regards!

**Comment by stla** [comment]
No idea, I never used **sf**.

**Comment by arthurwelle** [comment]
Well, it was worth the shot! Thanks anyway!
